#pragma once

bool tShirtsOpened = false;
bool beltsOpened = false;
bool eyewearOpened = false;
bool handsOpened = false;
bool headwearOpened = false;
bool headwear2Opened = false;
bool masksOpened = false;
bool scarvesOpened = false;
bool bellyOpened = false;
bool earsOpened = false;
bool fingersOpened = false;
bool neckOpened = false;
bool necklaceOpened = false;
bool necklaceLongOpened = false;
bool noseOpened = false;
bool wristsOpened = false;
bool feetOpened = false;
bool jacketsOpened = false;
bool jackets2Opened = false;
bool legsOpened = false;
bool legs2Opened = false;
bool shirtsOpened = false;
bool shortsleeveShirtsOpened = false;
bool socksOpened = false;
bool suitOpened = false;
bool sweatersOpened = false;
bool tanktopOpened = false;
bool torsoExtraOpened = false;
bool underclothingOpened = false;
bool tailOpened = false;
bool underwearOpened = false;
bool underwearBottomOpened = false;
bool underwearExtra1Opened = false;
bool underwearExtra2Opened = false;
bool underwearTopOpened = false;
bool handheldOpened = false;
bool wearableOpened = false;
bool communicationOpened = false;
bool electronicOpened = false;
bool containersOpened = false;
bool keysOpened = false;
bool locksOpened = false;
bool campingOpened = false;
bool cookingOpened = false;
bool farmingToolsOpened = false;
bool fertilizerOpened = false;
bool fishingOpened = false;
bool seeds2Opened = false;
bool trappingOpened = false;
bool forageOpened = false;
bool fruitOpened = false;
bool grainsOpened = false;
bool miscellaneous2Opened = false;
bool miscellaneous2p5Opened = false;
bool sweetsOpened = false;
bool vegetableOpened = false;
bool cannedFoodOpened = false;
bool pickledFoodOpened = false;
bool evolvedRecipeOpened = false;
bool preparedOrCookedOpened = false;
bool spiceOpened = false;
bool drinkOpened = false;
bool refillableOpened = false;
bool fishOpened = false;
bool gameOpened = false;
bool proteinOpened = false;
bool leisureOpened = false;
bool mapOpened = false;
bool recipeMagazineOpened = false;
bool skillbookOpened = false;
bool sritableOpened = false;
bool electricalOpened = false;
bool fabricOpened = false;
bool hairproductsOpened = false;
bool lightbulbOpened = false;
bool metalworkOpened = false;
bool miscellaneous3Opened = false;
bool paintOpened = false;
bool seedsOpened = false;
bool woodworkOpened = false;
bool bandagesOpened = false;
bool disinfectantsOpened = false;
bool medicalequipmentOpened = false;
bool pharmaceuticalsOpened = false;
bool herbsOpened = false;
bool poulticesOpened = false;
bool miscellaneous4Opened = false;
bool materialsOpened = false;
bool miscellaneous5Opened = false;
bool recipeMagazine2Opened = false;
bool skillBook2Opened = false;
bool toolsOpened = false;
bool weaponsOpened = false;
bool writableOpened = false;
bool brakeOpened = false;
bool doorOpened = false;
bool gasTankOpened = false;
bool generalPartOpened = false;
bool mufflerOpened = false;
bool seatOpened = false;
bool suspensionOpened = false;
bool tireOpened = false;
bool windowOpened = false;
bool axeOpened = false;
bool handgunsOpened = false;
bool improvisedOpened = false;
bool longBladeOpened = false;
bool longBluntOpened = false;
bool longBlunt2Opened = false;
bool rilesOpened = false;
bool shortBladeOpened = false;
bool shortBluntOpened = false;
bool shotgunsOpened = false;
bool spearOpened = false;
bool throwablesOpened = false;

std::vector<ItemMap> belts;
std::vector<ItemMap> eyewear;
std::vector<ItemMap> hands;
std::vector<ItemMap> headwear;
std::vector<ItemMap> headwear2;
std::vector<ItemMap> masks;
std::vector<ItemMap> scarves;
std::vector<ItemMap> belly;
std::vector<ItemMap> ears;
std::vector<ItemMap> fingers;
std::vector<ItemMap> neck;
std::vector<ItemMap> necklace;
std::vector<ItemMap> necklaceLong;
std::vector<ItemMap> nose;
std::vector<ItemMap> wrists;
std::vector<ItemMap> feet;
std::vector<ItemMap> jackets;
std::vector<ItemMap> jackets2;
std::vector<ItemMap> legs;
std::vector<ItemMap> legs2;
std::vector<ItemMap> shirts;
std::vector<ItemMap> shortsleeveShirts;
std::vector<ItemMap> socks;
std::vector<ItemMap> suit;
std::vector<ItemMap> sweaters;
std::vector<ItemMap> tanktop;
std::vector<ItemMap> torsoExtra;
std::vector<ItemMap> underclothing;
std::vector<ItemMap> tail;
std::vector<ItemMap> underwear;
std::vector<ItemMap> underwearBottom;
std::vector<ItemMap> underwearExtra1;
std::vector<ItemMap> underwearExtra2;
std::vector<ItemMap> underwearTop;
std::vector<ItemMap> handheld;
std::vector<ItemMap> wearable;
std::vector<ItemMap> communication;
std::vector<ItemMap> electronic;
std::vector<ItemMap> containers;
std::vector<ItemMap> keys;
std::vector<ItemMap> locks;
std::vector<ItemMap> camping;
std::vector<ItemMap> cooking;
std::vector<ItemMap> farmingTools;
std::vector<ItemMap> fertilizer;
std::vector<ItemMap> fishing;
std::vector<ItemMap> seeds2;
std::vector<ItemMap> trapping;
std::vector<ItemMap> forage;
std::vector<ItemMap> fruit;
std::vector<ItemMap> grains;
std::vector<ItemMap> miscellaneous2;
std::vector<ItemMap> miscellaneous2p5;
std::vector<ItemMap> sweets;
std::vector<ItemMap> vegetable;
std::vector<ItemMap> cannedFood;
std::vector<ItemMap> pickledFood;
std::vector<ItemMap> evolvedRecipe;
std::vector<ItemMap> preparedOrCooked;
std::vector<ItemMap> spice;
std::vector<ItemMap> drink;
std::vector<ItemMap> refillable;
std::vector<ItemMap> fish;
std::vector<ItemMap> game;
std::vector<ItemMap> protein;
std::vector<ItemMap> leisure;
std::vector<ItemMap> map;
std::vector<ItemMap> recipeMagazine;
std::vector<ItemMap> skillbook;
std::vector<ItemMap> sritable;
std::vector<ItemMap> electrical;
std::vector<ItemMap> fabric;
std::vector<ItemMap> hairproducts;
std::vector<ItemMap> lightbulb;
std::vector<ItemMap> metalwork;
std::vector<ItemMap> miscellaneous3;
std::vector<ItemMap> paint;
std::vector<ItemMap> seeds;
std::vector<ItemMap> woodwork;
std::vector<ItemMap> bandages;
std::vector<ItemMap> disinfectants;
std::vector<ItemMap> medicalequipment;
std::vector<ItemMap> pharmaceuticals;
std::vector<ItemMap> herbs;
std::vector<ItemMap> poultices;
std::vector<ItemMap> miscellaneous4;
std::vector<ItemMap> materials;
std::vector<ItemMap> miscellaneous5;
std::vector<ItemMap> recipeMagazine2;
std::vector<ItemMap> skillBook2;
std::vector<ItemMap> tools;
std::vector<ItemMap> weapons;
std::vector<ItemMap> writable;
std::vector<ItemMap> brake;
std::vector<ItemMap> door;
std::vector<ItemMap> gasTank;
std::vector<ItemMap> generalPart;
std::vector<ItemMap> muffler;
std::vector<ItemMap> seat;
std::vector<ItemMap> suspension;
std::vector<ItemMap> tire;
std::vector<ItemMap> window;
std::vector<ItemMap> axe;
std::vector<ItemMap> handguns;
std::vector<ItemMap> improvised;
std::vector<ItemMap> longBlade;
std::vector<ItemMap> longBlunt;
std::vector<ItemMap> longBlunt2;
std::vector<ItemMap> riles;
std::vector<ItemMap> shortBlade;
std::vector<ItemMap> shortBlunt;
std::vector<ItemMap> shotguns;
std::vector<ItemMap> spear;
std::vector<ItemMap> throwables;
std::vector<ItemMap> tShirts;