#pragma once

const std::map<std::string, std::string> CN_STRINGS = {
    {"themes", "主题"},
    {"focusInputs", "焦点输入"},
    {"defaultTheme", "默认"},
    {"purpleRetroTheme", "紫色复古"},
    {"blueRetroTheme", "蓝色复古"},
    {"language", "语言"},
    {"english", "英语"},
    {"chinese", "中文"},
    {"russian", "俄语"},
    {"polish", "抛光"},
    {"portuguese", "葡萄牙語"},
    {"add_level_to_perks", "增加特权等级："},
    {"perk_level", "特权等级"},
    {"perk_list", "特权列表"},
    {"build_cheat", "建造作弊"},
    {"enable_build_cheat", "启用建造作弊"},
    {"farming_cheat", "农场作弊"},
    {"enable_farming_cheat", "启用农场作弊"},
    {"health_cheat", "生命作弊"},
    {"enable_health_cheat", "启用生命作弊"},
    {"mechanics_cheat", "机械作弊"},
    {"enable_mechanics_cheat", "启用机械作弊"},
    {"movables_cheat", "可移动作弊"},
    {"enable_movables_cheat", "启用可移动作弊"},
    {"god_mode", "上帝模式"},
    {"enable_god_mode", "为小人启用上帝模式"},
    {"no_clip", "无碰撞"},
    {"toggle_no_clip", "切换小人的无碰撞模式"},
    {"invincible", "无敌"},
    {"make_player_invincible", "使小人无敌"},
    {"invisible", "隐身"},
    {"make_player_invisible", "使小人隐身"},
    {"ghost_mode", "幽灵模式"},
    {"enable_ghost_mode", "为小人启用幽灵模式"},
    {"zombies_dont_attack", "僵尸不攻击"},
    {"zombies_dont_attack_tooltip", "僵尸会把你当作目标，但不会攻击你"},
    {"unlimited_carry", "无限携带"},
    {"allow_unlimited_carry", "允许小人携带无限物品"},
    {"unlimited_endurance", "无限耐力"},
    {"give_unlimited_endurance", "给予小人无限耐力"},
    {"no_recoil_delay", "无后坐力延迟"},
    {"remove_recoil_delay", "移除小人的后坐力延迟"},
    {"no_melee_delay", "无近战延迟"},
    {"remove_melee_delay", "移除小人的近战延迟"},
    {"tester", "测试员"},
    {"test_new_features", "测试新功能"},
    {"misc_tabs", "杂项标签"},
    {"misc_1", "杂项1"},
    {"misc_2", "杂项2"},
    {"available_configs", "可用配置："},
    {"available_options", "可用选项："},
    {"add_new_config", "添加新配置"},
    {"config_name", "配置名称"},
    {"save", "保存"},
    {"selected_config", "选定的配置：%s"},
    {"load_selected_config", "加载选定的配置"},
    {"save_edited_config", "保存已编辑的配置"},
    {"remove_selected_config", "删除选定的配置"},
    {"remove_confirmation", "确定要删除选定的配置吗？"},
    {"yes", "是"},
    {"no", "否"},
    {"config_name_exists", "配置名称已存在，请选择其他名称。"},
    {"uc_thread", "线程"},
    {"project_github", "项目的GitHub"},
    {"red_github", "Red的GitHub"},
    {"okie_github", "Okie的GitHub"},
    {"made_by_red_and_okie", "由Redfane和Okie制作"},
    {"timed_action_instant_cheat", "定时动作即时作弊"},
    {"timed_action_instant_cheat_tooltip", "启用定时动作的即时完成"},
    {"start_reading", "开始阅读"},
    {"start_reading_tooltip", "开始阅读一本书"},
    {"show_admin_tag", "显示管理员标签"},
    {"show_admin_tag_tooltip", "为小人显示GM标签"},
    {"convert_to_sandwich_maker", "转换为寡妇制造者"},
    {"convert_to_sandwich_maker_tooltip", "将小人角色转换为寡妇制造者"},
    {"set_ranged_weapon_empty", "将远程武器设为空"},
    {"set_ranged_weapon_empty_tooltip", "将小人的远程武器设为空"},
    {"playerlist_window_title", "小人列表窗口"},
    { "items_window_title", "物品窗口" },
    { "categories_tab_bar", "分类" },
    { "Clothing", "服装" },
    { "Equipment", "装备" },
    { "Food", "食物" },
    { "Literature", "文学" },
    { "Medical", "医疗" },
    { "Materials", "材料" },
    { "Misc", "杂项" },
    { "Vehicle", "车辆" },
    { "Weapons", "武器" },
    { "category_not_implemented", "该分类的表尚未实现。" },
    { "add_item_with_base_id", "使用基本ID添加物品" },
    { "amount", "数量" },
    { "add_item_button", "添加物品" },
    { "added_item", "添加了基本ID为的物品" },
    { "inventory_items", "库存物品" },
    { "inventory_table_name", "库存" },
    { "column_name", "名称" },
    { "column_baseid", "基本ID" },
    { "selected_item", "选定的物品" },
    { "drag_text", "拖动 %s" },
    { "context_name", "名称：%s" },
    { "context_baseid", "基本ID：%s" },
    { "button_inspect", "检查" },
    { "context_amount", "数量" },
    { "context_add", "添加" },
    { "item_added", "[+] [x%d] | 添加物品" },
    { "item_text", "物品：%s" },
    { "main_window_title", "Esd.PZ | 第五代版本" },
    { "menu_items", "物品" },
    { "menu_playerslist", "小人列表" },
    { "tab_player", "小人" },
    { "tab_skills", "技能" },
    { "tab_misc", "杂项" },
    { "tab_style", "样式" },
    { "tab_config", "配置" },
    { "tab_settings", "设置" },
    { "tab_about", "关于" },
    { "terminal_window_title", "终端窗口" },
    { "terminal_clear_button", "清除终端" },
    { "terminal_copy_button", "复制日志" },
    { "terminal_scroll_checkbox", "滚动到底部" },
    { "terminal_export_button", "导出" },
    { "terminal_export_failed", "无法打开文件：" }
};
